---
kind: pipeline
type: docker
name: default

steps:
  - name: cmake
    image: registry.cn-beijing.aliyuncs.com/azzbcc/cmake
    volumes:
      - name: build
        path: /drone/build
    commands:
      - cd /drone/build
      - cmake /drone/src

  - name: compile
    image: registry.cn-beijing.aliyuncs.com/azzbcc/cmake
    pull: never
    volumes:
      - name: build
        path: /drone/build
    commands:
      - cmake --build /drone/build -- -j $(nproc)

  - name: test
    image: registry.cn-beijing.aliyuncs.com/azzbcc/cmake
    pull: never
    volumes:
      - name: build
        path: /drone/build
    commands:
      - cd /drone/build
      - ctest

volumes:
  - name: build
    temp: { }

---
kind: pipeline
type: docker
name: memcheck

steps:
  - name: cmake
    image: registry.cn-beijing.aliyuncs.com/azzbcc/cmake
    volumes:
      - name: build
        path: /drone/build
    commands:
      - cd /drone/build
      - cmake -DENABLE_MEMORY_CHECK=ON /drone/src

  - name: compile
    image: registry.cn-beijing.aliyuncs.com/azzbcc/cmake
    pull: never
    volumes:
      - name: build
        path: /drone/build
    commands:
      - cmake --build /drone/build -- -j $(nproc)

  - name: test
    image: registry.cn-beijing.aliyuncs.com/azzbcc/cmake
    pull: never
    volumes:
      - name: build
        path: /drone/build
    commands:
      - cd /drone/build
      - ctest -T memcheck

volumes:
  - name: build
    temp: { }

