---
kind: pipeline
type: docker
name: default

clone:
  disable: true

steps:
  - name: clone
    image: alpine/git
    commands:
      - git clone https://proxy.ananwork.com/github.com/$DRONE_REPO.git .
      - git checkout $DRONE_COMMIT

  - name: cmake
    image: registry.cn-beijing.aliyuncs.com/azzbcc/cmake
    volumes:
      - name: build
        path: /drone/build
    commands:
      - cd /drone/build
      - cmake /drone/src

  - name: compile
    image: registry.cn-beijing.aliyuncs.com/azzbcc/cmake
    pull: never
    volumes:
      - name: build
        path: /drone/build
    commands:
      - cmake --build /drone/build -- -j $(nproc)

  - name: test
    image: registry.cn-beijing.aliyuncs.com/azzbcc/cmake
    pull: never
    volumes:
      - name: build
        path: /drone/build
    commands:
      - cd /drone/build
      - ctest --stop-on-failure --output-on-failure

volumes:
  - name: build
    temp: { }

---
kind: pipeline
type: docker
name: memcheck

clone:
  disable: true

steps:
  - name: clone
    image: alpine/git
    commands:
      - git clone https://proxy.ananwork.com/github.com/$DRONE_REPO.git .
      - git checkout $DRONE_COMMIT

  - name: cmake
    image: registry.cn-beijing.aliyuncs.com/azzbcc/cmake
    volumes:
      - name: build
        path: /drone/build
    commands:
      - cd /drone/build
      - cmake -DENABLE_MEMORY_CHECK=ON /drone/src

  - name: compile
    image: registry.cn-beijing.aliyuncs.com/azzbcc/cmake
    pull: never
    volumes:
      - name: build
        path: /drone/build
    commands:
      - cmake --build /drone/build -- -j $(nproc)

  - name: test
    image: registry.cn-beijing.aliyuncs.com/azzbcc/cmake
    pull: never
    volumes:
      - name: build
        path: /drone/build
    commands:
      - ulimit -n 1024
      - cd /drone/build
      - ctest --stop-on-failure --output-on-failure -T memcheck

volumes:
  - name: build
    temp: { }

